@pokenae_WebApp_HostAddress = https://localhost:7255

POST https://pokenae-hrbndabnb6btgtbq.japaneast-01.azurewebsites.net/api/Values
Content-Type: application/json

{
    "id": "KARINA",
    "name": "KARINA",
    "memo": "memomo",
    "aa": "test"
}

###

POST {{pokenae_WebApp_HostAddress}}/api/values
Content-Type: application/json

{
    "id": "KARINAtest",
    "name": "KARINA",
    "memo": "memomo",
    "aa": "test"
}

###

GET {{pokenae_WebApp_HostAddress}}/api/cp_gart/te

###



GET {{pokenae_WebApp_HostAddress}}/api/values

###

GET https://pokenae-hrbndabnb6btgtbq.japaneast-01.azurewebsites.net/api/values

###


POST {{pokenae_WebApp_HostAddress}}/api/collectionassistancetool
Content-Type: application/json

{
  
    "spreadsheetId": "15vjM0HD16LGA7f9hLZC3DZIZaYnbOD41rPKI5gezh0c",
    "id": "KARINAtest",
    "name": "オトスパス",
    "memo": "memomo",
    "trainer": "スグリ",
    "aab": "test"
}

###

@spreadsheetId=15vjM0HD16LGA7f9hLZC3DZIZaYnbOD41rPKI5gezh0c
@sheetName=Column
GET {{pokenae_WebApp_HostAddress}}/api/collectionassistancetool/{{spreadsheetId}}/{{sheetName}}

###
